[package]
name = "advent_of_code_2020"
version = "1.0.0"
authors = ["Stuart Kent"]
edition = "2018"

[dependencies]
enum-ordinalize = "3.1.8"
itertools = "0.9.0"
lazy_static = "1.4.0"
regex = "1.4.2"
